server:
  port: 8080


spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/five_online?serverTimezone=UTC
    username: root
    password: 12345678


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.five.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      five:
        mapper: debug
        service: info
        controller: info
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
#jwt相关配置
five:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: hello
    # 设置jwt过期时间,360天 60*60*24*30*12
    ttl: 31104000

