server:
  address: 0.0.0.0


spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/five_online?serverTimezone=UTC
    username: root
    password: 12345678


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.five.pojo.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      five:
        mapper: debug
        service: info
        controller: info
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
five:
  jwt:
    secret-key: hello
    ttl: 31104000

